---
title: "Diamond Pricing Analysis"
author: "Joe Georger"
date: "10/26/2019"
output: html_document
---
### The Data
I spent a LOT of time in the "pre-discovery" phase looking for a suitable data set at UCI and Kaggle, one that combined a manageable number of features and observations as well as feature labels in a field that I had enough domain knowledge in to feel comfortable formulating a problem and drawing conclusions. I eventually chose a dataset based upon diamond pricing that seemed to have a good balance of number of features and observations, and I know a bit about the domain having been forced by "tradition" to purchase a diamond engagement ring.

The diamond pricing dataset was downloaded from <https://www.kaggle.com/shivam2503/diamonds/download>. It contains 53940 observations of 11 variables, including the "4 C's" that most diamond shoppers are familiar with: Carat, Cut, Color, and Clarity. The other observation of note is the price, which this app will predict using linear regression (under the tab of the same name.) Here is the entire list of features, taken from the aforementioned website:

'price': price in US dollars (\$326--\$18,823)

'carat': weight of the diamond (0.2--5.01)

'cut': quality of the cut (Fair, Good, Very Good, Premium, Ideal)

'color': diamond colour, from J (worst) to D (best)

'clarity' a measurement of how clear the diamond is (I1 (worst), SI2, SI1, VS2, VS1, VVS2, VVS1, IF (best))

'x' length in mm (0--10.74)

'y' width in mm (0--58.9)

'z' depth in mm (0--31.8)

'depth' total depth percentage = z / mean(x, y) = 2 * z / (x + y) (43--79)

'table' width of top of diamond relative to widest point (43--95)

It will be very interesting to see if indeed, the basic 4C's are enough to predict a diamond's price, or if other features such as depth or table are also important.

The data was quite clean, with no missing values. I did not see a need to do any data preparation for this analysis. I created a histogram tab that allows one to see the distribution of all the features in the dataset.

For model planning I used a scatterplot, included here, that showed a promising linear relationship between caret and price. This led me to start thinking about linear regression as the algorithm to base my model upon.

### The Algorithm
I chose Linear Regression as the most suitable algorithm to be applied to this data. Each diamond is measured or categorized and a price is given. It seemed obvious to investigate to what degree the various measurements or categories affected price. Linear regression is used to estimate a continous variable as a linear function of other variables, and these input variables could be continuous or discrete. Here, we aim to output continuous variable price, using one or more of the other features present in our dataset. Several of our input variables are discrete, namely cut, color, and clarity. For these categorical variables, they are expanded (behind the scenes in R) to a set of indicator variables. For example, color has 7 levels, this would be expanded to 7 variables, having a 0 if not in that category, or a 1 if it is. It is also important to note that our discrete fields have a modest number of distinct values - too many would be a problem for linear regression. here we have between 5 and 7.

Linear regression involves solving for the coefficients $\beta$ in
$$y_{i}=\beta_{0}+\beta_{1}x_{i}+\epsilon_{i}, i=1,...n$$
such that the residuals $e_{i}$ - which is the difference of the fitted value $y_{pred}$ and the observed value $y_{ref}$ - is minimized. The solution can be had by the *Ordinary Least Squares Method*, which involves a matrix inversion. Further reading on OLS: <https://en.wikipedia.org/wiki/Ordinary_least_squares>

Confidence Interval - quantifies error between sample metric and true metric due to sampling randomness.

### Conclusions
Linear regression does a good job of predicting price. One will see that carat (size) is the most important predictor, followed by clarity, color, and cut. Using the 4C's the linear regression coefficient of determination $R^2$ exceeds 0.92, meaning that 92% of the variance in price is acconted for in the model. The lesser-known fields of depth and table increase $R^2$ by minute amounts, so we have verified the common wisdom that the 4C's are indeed good at predicting a diamond's price.

While the linear regression does a good job of prediction overall, one cannot help but notice that the model is predicting negative prices for some of the inexpensive diamonds, up to about $2500. We see a little bit of a curve to the data when comparing the 4C regression against the line of true prediction. This leads to the conlusion that it might be worth trying a non-linear model to see if that could better capture these effects.

Note on forcing regression through the origin: I did experiment with forcing this, and $R^2$ decreased and the predictions were non-negative when I chose a single independent variable. Choosing multiple variables I noticed negative predictive prices return. As this practice is somewhat controversial (according to a Google search) I decided to not include the option.
